services:
  - type: web
    name: proposalai-backend
    env: node
    plan: free
    buildCommand: chmod +x render-deploy.sh && ./render-deploy.sh
    startCommand: cd src/server && PRISMA_QUERY_ENGINE_BINARY=node_modules/.prisma/client/libquery_engine-linux-musl.so.node npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: CORS_ORIGIN
        sync: false 