services:
  - type: web
    name: proposalai-backend
    env: node
    plan: free
    buildCommand: chmod +x render-docker.sh && ./render-docker.sh
    startCommand: cd src/server && PRISMA_QUERY_ENGINE_BINARY=node_modules/.prisma/client/libquery_engine-debian-openssl-3.0.x.so.node npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: CORS_ORIGIN
        sync: false 