services:
  - type: web
    name: proposalai-backend
    env: node
    plan: free
    buildCommand: chmod +x render-final.sh && ./render-final.sh
    startCommand: cd src/server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: CORS_ORIGIN
        sync: false 